### ISSUE TITLE
Jumps back to fancy graph when it really shouldn't

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#133] opened 2020-10-15 10:36 UTC
When I look at a fast graph and increase the range to, say, 1000 days, the tab freezes for something like a minute and then presents the fancy graph. I'm assuming the page would have frozen a significantly shorter time using the fast graph.

**Comment by I-Al-Istannen** [comment] 2020-10-15 10:50
It probably jumps back because a few thousand datapoints isn't that much (I assume you didn't select all too many dimensions).

The graph rendering seems to be fine as well, but *it waits a few seconds until it even starts fetching new data*. I couldn't reproduce that on our instance, but a quick profile on yours showed it spent around 90% of the time *inside Vue*, the UI framework, calculating and updating dependencies between the displayed state and the internal one.

The page would probably be frozen just as long if it picked the fast graph, the graph computation and rendering time seemed to be quite normal.

I will have a look at reproducing it locally and tracking down where exactly it updates way too many dependent bindings.

**Comment by I-Al-Istannen** [comment] 2020-10-15 12:03
I partially retract my statement. Echarts doesn't seem to like big data ranges, it can handle more points when the date range is small and there are a few series apparently.
I lowered the threshold by around 20.000, you can always manually switch back to the fancy graph if you want to, after all.

The other big problem was that it updated its data, waited for the current graph to fully render and *then* selected the more fitting graph.

I will see if that's enough, but it looks like quite a nice improvement with our dummy data (a few hundred thousand points of perlin noise).

**Comment by I-Al-Istannen** [comment] 2020-10-20 17:49
I think that might've actually been enough. Loading https://velcom.aaaaaaah.de/repo-detail/2ff64fb6-5996-4bfd-a99e-86ebcd6441c7?dimensions=Beat this:cats in the cradle:magic:oracle:size::BenchMe:cats in the cradle:magic:oracle:size completes in around 8 seconds, but only 1.4 are spent on drawing graphs. The rest is waiting for the backend to respond (and that should get faster once the listener branch is merged as well).

We can probably merge the UI changes to stable ourselves in the next few days, once #135 landed so you can try it out on the lean instance.

**Comment by Kha** [comment] 2020-10-21 08:37
Yep, sounds good!

**Closed** 2020-10-26 09:20 UTC
Labels: bug, frontend
